name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  deploy_live:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy live site
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PIXEL_WORLD_8CB9B }}"
          channelId: live
          projectId: pixel-world-8cb9b
